### ISSUE TITLE
Are these queries run by calling the GPU through the rapids library?

### ISSUE THREAD

**Issue by YeahNew** [rapidsai/tpcx-bb#100]
Hi,the rapids library can call the GPU. Can your queries be run on the GPU?

**Comment by beckernick** [comment]
Hi @YeahNew . Yes, this repository provides implementations of the TPCx-BB queries using RAPIDS libraries, which run on GPUs. Please see the README for more information.

Closing this as the question is answered, but please feel free to reopen it.
