### ISSUE TITLE
Fix remaining unsafe string path creations

### ISSUE THREAD

**Issue by beckernick** [rapidsai/tpcx-bb#129]
https://github.com/rapidsai/tpcx-bb/pull/80 resolved most path issues, but we still can hit this when we circumvent the scheduler and mainline API and use delayed cudf reads.

**Comment by beckernick** [comment]
This is the root cause of #128

**Comment by VibhuJawa** [comment]
Closed by https://github.com/rapidsai/tpcx-bb/pull/130
