### ISSUE TITLE
Add ability to set configuration options for BlazingContext

### ISSUE THREAD

**Issue by williamBlazing** [rapidsai/tpcx-bb#22]
We need to implement a way to set configuration options for the BlazingContext that is not hardcoded in every query. 

The configuration options are set in BlazingContext as a dictionary. For example:
```
config_options = {}
config_options['JOIN_PARTITION_SIZE_THRESHOLD'] = 300000000
config_options['BLAZING_DEVICE_MEM_CONSUMPTION_THRESHOLD'] = 0.8
config_options['BLAZING_LOGGING_DIRECTORY'] = 'blazing_log'
config_options['MAX_DATA_LOAD_CONCAT_CACHE_BYTE_SIZE'] = 400000000
bc = BlazingContext(
        dask_client=client,
        pool=True,
        network_interface=os.environ.get("INTERFACE", "eth0"),
        config_options = config_options
    )
```
We should implement a way to set those for every query either using environment variables:

```
config_options = {}
config_options['JOIN_PARTITION_SIZE_THRESHOLD'] = os.environ.get("JOIN_PARTITION_SIZE_THRESHOLD", 300000000)
config_options['BLAZING_DEVICE_MEM_CONSUMPTION_THRESHOLD'] = os.environ.get("BLAZING_DEVICE_MEM_CONSUMPTION_THRESHOLD", 0.8)
config_options['BLAZING_LOGGING_DIRECTORY'] = os.environ.get("BLAZING_LOGGING_DIRECTORY", 'blazing_log')
config_options['MAX_DATA_LOAD_CONCAT_CACHE_BYTE_SIZE'] =  os.environ.get("MAX_DATA_LOAD_CONCAT_CACHE_BYTE_SIZE", 300000000)
bc = BlazingContext(
        dask_client=client,
        pool=True,
        network_interface=os.environ.get("INTERFACE", "eth0"),
        config_options = config_options
    )
```

And then adding the following to `cluster-startup.sh`
```
# Check for and set BlazingContext config_options as environment variables
if [ -z "$JOIN_PARTITION_SIZE_THRESHOLD" ]
then
      export JOIN_PARTITION_SIZE_THRESHOLD=300000000
fi
if [ -z "$BLAZING_DEVICE_MEM_CONSUMPTION_THRESHOLD" ]
then
      export BLAZING_DEVICE_MEM_CONSUMPTION_THRESHOLD=0.8
fi
if [ -z "$BLAZING_LOGGING_DIRECTORY" ]
then
      export BLAZING_LOGGING_DIRECTORY="blazing_log"
fi
if [ -z "$MAX_DATA_LOAD_CONCAT_CACHE_BYTE_SIZE" ]
then
      export MAX_DATA_LOAD_CONCAT_CACHE_BYTE_SIZE=300000000
fi
```

**Comment by beckernick** [comment]
Thanks @williamBlazing , this look great. Pushing BlazingContext configuration to the actual configuration makes sense.

If each query remains an independent Python script, is it proper for each query to create its own BlazingContext using the above configuration? Or, must the context be set up only once regardless of how many queries we run?

**Comment by randerzander** [comment]
In end to end (sequential query runs), we save significant time by re-using Dask Client objects. I suspect avoiding repeated BlazingContext creation costs will save substantial time at SF1k.

**Comment by beckernick** [comment]
> In end to end (sequential query runs), we save significant time by re-using Dask Client objects. I suspect avoiding repeated BlazingContext creation costs will save substantial time at SF1k.

I agree that we will want to do this. I suspect we'll want the queries to do something like `attach_to_context`, analogous to `attach_to_cluster`. With that said, I believe the primary time saver in the end-to-end sequential query runs is the ability to run the client in the same Python process, which means we only pay the import costs once.

**Comment by williamBlazing** [comment]
Most of the cost of creating a BlazingContext is initializing the allocator. So if we are just re-using the allocator, the cost will be a little less, but even still, i think that re-using the context, should result in a net savings

**Comment by williamBlazing** [comment]
From our conversation on the TPCX-BB meeting we have the following requirements:
- create a new script similar but separate from `cluster-startup.sh` called `bsql-cluster-startup.sh`. This script will allow for setting allocator behavior and also config_options for `BlazingContext`.
- The scripts should create only one BlazingContext and pass it to all the queries  (this will be handled by @beckernick )

The requirements for allocator behavior:
- The allocator should be able to be set for 'default','managed' or 'existing'. If the allocator is set to existing, it should create the RMM pool allocator the way it is set in `cluster-startup.sh`. If allocator is NOT set to existing, then the RMM pool allocator should not be created external to the BlazingContext at all.
- You should also be able to set BlazingContext parameters: `pool` = True | False and `initial_pool_size`

The requirements for parameters to set for `config_options`. We want to be able to configure the following parameters. Note that here they are set with their default:
config_options['JOIN_PARTITION_SIZE_THRESHOLD'] = 300000000
config_options['BLAZING_DEVICE_MEM_CONSUMPTION_THRESHOLD'] = 0.8
config_options['BLAZING_LOGGING_DIRECTORY'] = 'blazing_log'
config_options['MAX_DATA_LOAD_CONCAT_CACHE_BYTE_SIZE'] = 400000000
config_options['BLAZING_CACHE_DIRECTORY'] = '/tmp/'

We should make it relatively easy to add more to this list.

**Comment by beckernick** [comment]
This has been resolved. BlazingSQL configuration options can be set in `xbb_tools.cluster_startup.get_config_options`
