### ISSUE TITLE
Update Q28 to use cuML APIs

### ISSUE THREAD

**Issue by beckernick** [rapidsai/tpcx-bb#50]
cuML now supports text vectorizers and some additional metrics. We should evaluate if cuML now provides the necessary functionality for vectorizers and estimator quality metrics. If it does, we should use them to simplify the code significantly.

**Comment by VibhuJawa** [comment]
Agreed, Once https://github.com/rapidsai/cuml/pull/2554  lands we should be able to delete a bunch of code and use the upstreamed code from cuml :-D

**Comment by beckernick** [comment]
This should now be possible

**Comment by VibhuJawa** [comment]
We also have  distributed `tf-idf` now so will switch this to use  that along with `Hashing-Vectorizer`

**Comment by VibhuJawa** [comment]
Closed by #104
