### ISSUE TITLE
[FEA] Automatically provide each node with access to sentiment files or data

### ISSUE THREAD

**Issue by beckernick** [rapidsai/tpcx-bb#53]
Queries 10, 18, and 19 require additional sentiment text files for part of the logic. With pure-dask, these queries can be read by the client process and distributed appropriately. The BSQL queries currently require each node to have access to these files and in the correct location.

We need to rework these to ensure all data is available to queries as appropriate, perhaps by replication of the files or explicit broadcasting of the data in memory. Or, perhaps we can assume existence of a shared filesystem, as these files are quite small and will likely not be much affected by IO considerations.

**Comment by beckernick** [comment]
The relevant portion of the queries is generally this segment:

https://github.com/rapidsai/tpcx-bb/blob/d21f152e5b210c871a0ab30859b1829b56c328d2/tpcx_bb/queries/q10/tpcx_bb_query_10_sql.py#L88-L93

cc @Christian8491 and @randerzander , who has been giving this some thought

**Comment by randerzander** [comment]
I believe #48 resolves this for q10 and q19.

**Comment by beckernick** [comment]
This has been resolved. Sentiment files are expected to be placed on the same mount as the data, which is required to be accessible from all nodes.
