### ISSUE TITLE
[BUG] Dask Q18 remove deprecated to_list() method   

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/tpcx-bb#87]
In `Q18` we currently have `targets.str.lower().tolist()`  call which has been depreciated . See below: 

https://github.com/rapidsai/tpcx-bb/blob/62a0833520e615f81316451cce7bad1fb019b37a/tpcx_bb/queries/q18/tpcx_bb_query_18.py#L141-L149

We should :

1.  Look into removing this `host`->`device`->`host` trip all together as this was added due to bugs with `serialization` of nvstrings but that should have now be fixed. 

2.  Centralize logic for both `dask` and `bsql` implementations. 

Related BSQL PR: https://github.com/rapidsai/tpcx-bb/pull/85/files

**Comment by beckernick** [comment]
Picking this up.
